In [2]:
import pandas as pd
train_data = pd.read_csv('C:/Users/Nkechi Ijeoma/Downloads/craigslist-carstrucks-data/car_train_data.csv')
train_data

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,drive,size,type,paint_color,image_url,description,county,state,lat,long
0,7088746062,https://greensboro.craigslist.org/ctd/d/cary-2...,greensboro,https://greensboro.craigslist.org,10299,2012.0,acura,tl,NaN,NaN,...,NaN,NaN,other,blue,https://images.craigslist.org/01414_3LIXs9EO33...,2012 Acura TL Base 4dr Sedan Offered by: B...,NaN,nc,35.7636,-78.7443
1,7088745301,https://greensboro.craigslist.org/ctd/d/bmw-3-...,greensboro,https://greensboro.craigslist.org,0,2011.0,bmw,335,NaN,6 cylinders,...,rwd,NaN,convertible,blue,https://images.craigslist.org/00S0S_1kTatLGLxB...,BMW 3 Series 335i Convertible Navigation Dakot...,NaN,nc,NaN,NaN
2,7088744126,https://greensboro.craigslist.org/cto/d/greens...,greensboro,https://greensboro.craigslist.org,9500,2011.0,jaguar,xf,excellent,NaN,...,NaN,NaN,NaN,blue,https://images.craigslist.org/00505_f22HGItCRp...,2011 jaguar XF premium - estate sale. Retired ...,NaN,nc,36.1032,-79.8794
3,7088743681,https://greensboro.craigslist.org/ctd/d/cary-2...,greensboro,https://greensboro.craigslist.org,3995,2004.0,honda,element,NaN,NaN,...,fwd,NaN,SUV,orange,https://images.craigslist.org/00E0E_eAUnhFF86M...,2004 Honda Element LX 4dr SUV Offered by: ...,NaN,nc,35.7636,-78.7443
4,7074612539,https://lincoln.craigslist.org/ctd/d/gretna-20...,lincoln,https://lincoln.craigslist.org,41988,2016.0,chevrolet,silverado k2500hd,NaN,NaN,...,NaN,NaN,NaN,NaN,https://images.craigslist.org/00S0S_8msT7RQquO...,"Shop Indoors, Heated Showroom!!!www.gretnaauto...",NaN,ne,41.1345,-96.2458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,7088762645,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,0,2011.0,ford,explorer,NaN,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00B0B_dH6DjAEsEH...,2011 Ford Explorer Limited AWD 4dr SUVÂ Mohr Mo...,NaN,or,44.9297,-123.0300
3996,7088762573,https://salem.craigslist.org/ctd/d/salem-2008-...,salem,https://salem.craigslist.org,0,2008.0,jeep,wrangler unlimited,NaN,NaN,...,4wd,NaN,SUV,NaN,https://images.craigslist.org/00x0x_1tvqQBa5dT...,2008 Jeep Wrangler Unlimited Sahara 4x4 4dr SU...,NaN,or,44.9297,-123.0300
3997,7088761779,https://salem.craigslist.org/ctd/d/salem-2012-...,salem,https://salem.craigslist.org,0,2012.0,ram,pickup 1500,NaN,NaN,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00q0q_5n6hZzQ36W...,2012 RAM Ram Pickup 1500 Sport 4x4 4dr Crew Ca...,NaN,or,44.9297,-123.0300
3998,7088761742,https://salem.craigslist.org/ctd/d/salem-2011-...,salem,https://salem.craigslist.org,0,2011.0,gmc,sierra 1500 slt,NaN,8 cylinders,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00i0i_mtrxLdNlWA...,POWER Buick GMC of SalemÂ Â Â Â Â Â Â Â STOCK #:Â Â D213...,NaN,or,44.9508,-122.9880
3999,7088760906,https://salem.craigslist.org/ctd/d/salem-2012-...,salem,https://salem.craigslist.org,0,2012.0,ram,pickup 1500,NaN,NaN,...,4wd,NaN,NaN,NaN,https://images.craigslist.org/00c0c_6bPpaVL4Fh...,2012 RAM Ram Pickup 1500 ST 4x4 4dr Crew Cab 5...,NaN,or,44.9297,-123.0300

In [7]:
train_data = train_data.drop(['url','image_url', 'region_url', 'lat', 'long', 'region', 'description', 'vin'], axis=1)
train_data

,id,region_url,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,vin,drive,size,type,paint_color,county,state
0,7088746062,https://greensboro.craigslist.org,10299,2012.0,acura,tl,NaN,NaN,gas,90186.0,clean,automatic,19UUA8F22CA003926,NaN,NaN,other,blue,NaN,nc
1,7088745301,https://greensboro.craigslist.org,0,2011.0,bmw,335,NaN,6 cylinders,gas,115120.0,clean,automatic,NaN,rwd,NaN,convertible,blue,NaN,nc
2,7088744126,https://greensboro.craigslist.org,9500,2011.0,jaguar,xf,excellent,NaN,gas,85000.0,clean,automatic,NaN,NaN,NaN,NaN,blue,NaN,nc
3,7088743681,https://greensboro.craigslist.org,3995,2004.0,honda,element,NaN,NaN,gas,212526.0,clean,automatic,5J6YH18314L006498,fwd,NaN,SUV,orange,NaN,nc
4,7074612539,https://lincoln.craigslist.org,41988,2016.0,chevrolet,silverado k2500hd,NaN,NaN,gas,NaN,clean,automatic,1GC1KWE85GF266427,NaN,NaN,NaN,NaN,NaN,ne
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,7088762645,https://salem.craigslist.org,0,2011.0,ford,explorer,NaN,NaN,gas,NaN,clean,automatic,1FMHK8F82BGA04422,4wd,NaN,SUV,NaN,NaN,or
3996,7088762573,https://salem.craigslist.org,0,2008.0,jeep,wrangler unlimited,NaN,NaN,gas,NaN,clean,manual,1J8GA59188L503833,4wd,NaN,SUV,NaN,NaN,or
3997,7088761779,https://salem.craigslist.org,0,2012.0,ram,pickup 1500,NaN,NaN,gas,NaN,clean,automatic,1C6RD7MT9CS173234,4wd,NaN,NaN,NaN,NaN,or
3998,7088761742,https://salem.craigslist.org,0,2011.0,gmc,sierra 1500 slt,NaN,8 cylinders,gas,62516.0,clean,automatic,3GTP2WE37BG371220,4wd,NaN,NaN,NaN,NaN,or
3999,7088760906,https://salem.craigslist.org,0,2012.0,ram,pickup 1500,NaN,NaN,gas,NaN,clean,automatic,1C6RD7KT1CS270933,4wd,NaN,NaN,NaN,NaN,or

In [5]:
train_data.columns

Index(['id', 'url', 'region', 'region_url', 'price', 'year', 'manufacturer',
       'model', 'condition', 'cylinders', 'fuel', 'odometer', 'title_status',
       'transmission', 'vin', 'drive', 'size', 'type', 'paint_color',
       'image_url', 'description', 'county', 'state', 'lat', 'long'],
      dtype='object')